spring:
  datasource:
    url: jdbc:mysql://192.168.31.20:3306/learning?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: learner
    password: study
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: debug
    com.macro.mall: debug
