spring:
  datasource:
    url: jdbc:mysql://192.168.31.20:3306/learning?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: learner
    password: study
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.31.20
    database: 0
    port: 6379
    password:
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.keepthinker.spring.springbootexample: debug