#server:
#  port: 9090
#spring:
#  application:
#    name: spring-boot-example-server
#  profiles:
#    active: dev #默认为开发环境

mybatis:
  mapper-locations: classpath:/mapping/*.xml

chatrobot:
  usePrefix: true
  # type default value defined in ConfigCenterHandler
#  type: adorable

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


