spring:
  datasource:
    url: jdbc:mysql://192.168.31.20:3306/learning?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: learner
    password: study
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    host: defined in config.properties
    database: 0
    port: 6379
    password:
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.keepthinker.spring.springbootexample: debug

dubbo:
  application:
    # 应用名称
    name: user-provider
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.keepthinker.spring.springbootexample.dubbo
  # 注册中心信息
  registry:
    address: zookeeper://192.168.31.20:2181
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
#    port: 20880

#eureka:
#  client:
#    serviceURL:
#      defaultZone: http://localhost:8900/eureka

nacos:
  config:
    server-addr: 192.168.31.20:8848