logging:
  level:
    root: info
    com.keepthinker.spring.springbootexample: debug

dubbo:
  application:
    # 应用名称
    name: user-consumer
  # 注册中心信息
  registry:
    address: zookeeper://192.168.31.20:2181
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.keepthinker.spring.springbootexample.dubbo
  protocol:
    # 协议名称
    name: dubbo
  consumer:
    filter: dubbo-invoker-filter