logging:
  level:
    root: info
    com.keepthinker.spring.springbootexample: debug

dubbo:
  application:
    # 应用名称
    name: user-consumer
  # 注册中心信息
  registry:
    address: nacos://192.168.1.9:8848
  protocol:
    # 协议名称
    name: dubbo
  consumer:
    filter: dubbo-invoker-filter

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.9:8848
